### ISSUE TITLE
For the second stage

### ISSUE THREAD

**Issue by corkiyao** [zhiyuan0112/TSBSR#1]
In the second stage, the pre-trained SwinIR model can produce a pe-sudo SR HSI image. But I have some problems: For example, the Houston2018 dataset is the size 1202 × 4172, and I split it into a training region and a testing region. For the training region, it will be cut into many training samples and these samples are responsible for the SSPSR or ERCSR, or other supervised competting methods. Whether the HSI training samples are also used to traing the unsupervised learning stage in this paper?
I really want to thanks for your appreciate help.

**Comment by zhiyuan0112** [comment]
In the unsupervised learning stage, our method does not use the HSI training samples. We perform unsupervised learning only on the testing region.
